groups:
  - name: Node_Exporter_Alerts
    rules:
      # 游뚿 Alerta: Uso alto de CPU en el nodo
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Uso alto de CPU en {{ $labels.instance }}"
          description: "El uso de CPU en {{ $labels.instance }} ha superado el 80% durante m치s de 2 minutos."

      # 游뚿 Alerta: Memoria baja en el nodo
      - alert: LowMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Memoria baja en {{ $labels.instance }}"
          description: "La memoria disponible en {{ $labels.instance }} es menor al 10%."

      # 游뚿 Alerta: Disco casi lleno
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Espacio en disco bajo en {{ $labels.instance }}"
          description: "El disco en {{ $labels.instance }} tiene menos del 10% de espacio disponible."

  - name: cAdvisor_Alerts
    rules:
      # 游뚿 Alerta: Uso alto de CPU en contenedor
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total{image!=""}[5m]) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Uso alto de CPU en contenedor {{ $labels.name }}"
          description: "El contenedor {{ $labels.name }} est치 usando m치s del 80% de CPU."

      # 游뚿 Alerta: Contenedor con uso de memoria excesivo
      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes{image!=""} / container_spec_memory_limit_bytes{image!=""}) * 100 > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Uso excesivo de memoria en contenedor {{ $labels.name }}"
          description: "El contenedor {{ $labels.name }} ha superado el 90% de su memoria asignada."

      # 游뚿 Alerta: Contenedor reinici치ndose con frecuencia
      - alert: ContainerFrequentRestarts
        expr: increase(container_restart_count{image!=""}[5m]) > 3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Reinicios frecuentes en contenedor {{ $labels.name }}"
          description: "El contenedor {{ $labels.name }} se ha reiniciado m치s de 3 veces en los 칰ltimos 5 minutos."

  
  - name: Node_Exporter_Alerts_SystemLoad
    rules:
      # 游뚿 Alerta: Alta carga del sistema en 1 minuto
      - alert: HighSystemLoad1m
        expr: node_load1 > (count(node_cpu_seconds_total{mode="user"}) * 1.5)
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Alta carga del sistema en 1 minuto en {{ $labels.instance }}"
          description: "La carga del sistema en {{ $labels.instance }} ha superado el 150% del n칰mero de CPUs durante m치s de 2 minutos."

      # 游뚿 Alerta: Alta carga del sistema en 5 minutos (m치s severa)
      - alert: HighSystemLoad5m
        expr: node_load5 > (count(node_cpu_seconds_total{mode="user"}) * 2)
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Alta carga del sistema en 5 minutos en {{ $labels.instance }}"
          description: "La carga del sistema en {{ $labels.instance }} ha superado el 200% del n칰mero de CPUs durante m치s de 5 minutos."

      # 游뚿 Alerta: Sobrecarga extrema del sistema en 15 minutos
      - alert: CriticalSystemLoad
        expr: node_load15 > (count(node_cpu_seconds_total{mode="user"}) * 3)
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Sobrecarga extrema en {{ $labels.instance }}"
          description: "La carga del sistema en {{ $labels.instance }} ha superado el 300% del n칰mero de CPUs durante m치s de 10 minutos."          
