server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://loki:3100/loki/api/v1/push"

clients:
  - url: http://$MASTER_IP:3100/loki/api/v1/push

scrape_configs:
  # Logs sistema
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  #Comandos usuarios
  - job_name: history
    static_configs:
    - targets:
        - localhost
      labels:
        job: history
        __path__: /home_server/*/.bash_history

  # Comandos Root
  - job_name: history_root
    static_configs:
    - targets:
        - localhost
      labels:
        job: history
        __path__: /root_user/.bash_history

  # Logs de contenedores.
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'


