[[servers]]
host = "fiware.app"
port = 389
use_ssl = false
start_tls = false
bind_dn = "CN=regis,OU=Registry,OU=Usuarios,OU=Entidad,OU=grupo-informatico,DC=fiware,DC=app"
bind_password = "xxxxxxxxxxxxxxxxxxcambiarxxxxxxx"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["DC=fiware,DC=app"]

group_search_filter = "(member=%d)"
group_search_base_dns = ["DC=fiware,DC=app"]

[servers.attributes]
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"

[[servers]]
host = "fiware02.app"
port = 389
use_ssl = false
start_tls = false
bind_dn = "CN=regis,OU=Registry,OU=Usuarios,OU=Entidad,OU=grupo-informatico,DC=fiware02,DC=app"
bind_password = "xxxxxxxxxxxxxxxxxxcambiarxxxxxxx"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["DC=fiware02,DC=app"]

group_search_filter = "(member=%d)"
group_search_base_dns = ["DC=fiware02,DC=app"]

[servers.attributes]
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"

